database:
  chroma_path: chroma
  data_path: data
documents:
  chunk_overlap: 80
  chunk_size: 800
  supported_formats:
  - pdf
  - md
  - txt
  - rtf
embedding:
  bedrock:
    aws_profile: default
    aws_region: us-east-1
    model: amazon.titan-embed-text-v1
  huggingface:
    api_key: ''
    cache_dir: ./cache
    model: sentence-transformers/all-MiniLM-L6-v2
  model: nomic-embed-text
  ollama:
    base_url: http://localhost:11434
    timeout: 120
  openai:
    api_key: ''
    model: text-embedding-3-small
  provider: ollama
llm:
  max_tokens: 2048
  model: llama3.1:latest
  ollama:
    base_url: http://localhost:11434
  openai:
    api_key: ''
    model: gpt-3.5-turbo
  provider: ollama
  temperature: 0.1
logging:
  level: INFO
  suppress_http: true
query:
  max_results: 5
  similarity_threshold: 0.0
